---
title: "Alejandro Martinez-Carrasco's CV"
author: Alejandro Martinez-Carrasco
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['style/dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1DAV6qURXI3cF77zc3cpIjKftcgwQa8NwWCxTZ28U__E/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
#datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _/home/amcalejandro/Data/POSTDOCS/mycv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/AMCalejandro/cv/raw/gh-pages/amc_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills("language")
```


Technologies {#technologies}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills("technology")
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [GitHub](https://github.com/AMCalejandro/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Alejandro Martinez Carrasco {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Work experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


<!-- These breaks just force a new page so section doesnt get cut off -->

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::


```{r}
CV %<>% print_section('teaching_positions')
```



```{r}
CV %<>% print_links()
```


Selected Publications {data-icon=book}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('academic_articles')
```

